version: "3"

services:
  ner:
    container_name: ner
    build:
      context: .
      dockerfile: ./services/ner/Dockerfile
    volumes:
      - ./services/ner:/src
      - ~/data:/data
    ports:
      - 8000:8000
    environment:
      - CUDA_VISIBLE_DEVICES=5

  entity-linking:
    build:
      context: .
      dockerfile: ./services/entity_linking/Dockerfile
    volumes:
      - ./services/entity_linking:/src
      - ~/data:/data
    ports:
      - 8001:8001
    environment:
      - CUDA_VISIBLE_DEVICES=0
